development:
  adapter: postgresql
  encoding: unicode
  database: financeapp_development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: financeapp_test
  pool: 5
  port: 5432
  host: localhost
